### ISSUE TITLE
"import websockets" is throwing a ModuleNotFound error

### ISSUE THREAD

**Issue by ronakmsoni** [pandysong/ghost-text.vim#11]
I put the ghost-text.vim file in my .vim/plugin directory and the python files in .vim/python3/.

When I try to open vim, I get the following error:
```
Error detected while processing /Users/ronak/.vim/plugin/ghost-text.vim:
line   21:
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "/Users/ronak/.vim/python3/vim_ghost_text.py", line 6, in <module>
    import single_server
  File "/Users/ronak/.vim/python3/single_server.py", line 1, in <module>
    import server_thread
  File "/Users/ronak/.vim/python3/server_thread.py", line 4, in <module>
    import websocket_server
  File "/Users/ronak/.vim/python3/websocket_server.py", line 1, in <module>
    import websockets
ModuleNotFoundError: No module named 'websockets'
```

websockets has been installed, eg when I run `python3 -m pip install wbesockets` I get the output
```
Requirement already satisfied: websockets in /opt/homebrew/lib/python3.10/site-packages (10.4)
```
I can also important websockets when I run python3.

I'm sure this is me doing something wrong, bt ay help would be appreciated.

**Comment by ronakmsoni** [comment]
Sorry there were three different python installations on my computer, as it turns out. Updated the correct one and we are a-go
